version: '3'
services:
  quasar:
    container_name: berlin
    command: quasar --version
    # restart: always
    build: .
    network_mode: host
    volumes:
      - ./:/app
      -  /dev/bus/usb:/dev/bus/usb